
// MACRO STATUS FOR COMMUNICATION MANAGER AND BASE CONTROLLER

//BASE STATUS MACRO
#define TO_GOAL 0
#define GOAL_OK 1
#define GOAL_FAIL 2
#define IDLE 3

//ARM STATUS MACRO
#define GRASP_FAIL 0
#define ARM_IDLE 1
#define ARM_RUNNING 2

//PICK AND PLACE MACRO

#define PICK 0
#define PLACE 1
