
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /locobot/rtabmap/depth/color/voxels
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
