local_costmap:
  static_map : false
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance : 0.5
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  plugins:
  - {name: laser_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: depth_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  - {name: social_layer, type: "social_navigation_layers::ProxemicLayer"}
